provider: local
path: ~/images
priority: 0
chunk_size: 128MB
compression_override: webp
headers:
  Authorization: Bearer Token
resources:
  - url: https://www.adobe.com/creativecloud/photography/discover/media_131179edca5f92db203e2b78cb8a308605afbc958.png
    name: perro
    priority: 10
    dest:
      path: ~/randproj/
    config:
      compression_override: avif
      quality: 95
  # - url: ftp://files.example.com/resource.mp4
  #   dest:
  #     provider: gdrive
  #     path: my-drive/Música
  #   name: video
  #   config:
  #     compression_override: av1
  # - url: https://example3.com/resource.mov
  #   dest:
  #     provider: s3
  #     path: movies
  #   name: movie
  #   config:
  #     compression_override: none